### ISSUE TITLE
Team section

### ISSUE THREAD

**Issue by JACHacks** [JACHacks/JACHacks-Website#10]
# Task

Add a section for the team members
Displays:
- [x] All team members photo
- [x] All team members names
- [x] All team members LinkedIn/GitHub
- [x] All team members role

# End result

Something that can give each viewer an idea of who the organizers are before the event.

**Comment by fehe-bo** [comment]
done
